#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-trimcluster
Version  : 0.1.2.1
Release  : 19
URL      : https://cran.r-project.org/src/contrib/trimcluster_0.1-2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/trimcluster_0.1-2.1.tar.gz
Summary  : Cluster Analysis with Trimming
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
No detailed description available

%prep
%setup -q -c -n trimcluster

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552942810

%install
export SOURCE_DATE_EPOCH=1552942810
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library trimcluster
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library trimcluster
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library trimcluster
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  trimcluster || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/trimcluster/DESCRIPTION
/usr/lib64/R/library/trimcluster/INDEX
/usr/lib64/R/library/trimcluster/Meta/Rd.rds
/usr/lib64/R/library/trimcluster/Meta/features.rds
/usr/lib64/R/library/trimcluster/Meta/hsearch.rds
/usr/lib64/R/library/trimcluster/Meta/links.rds
/usr/lib64/R/library/trimcluster/Meta/nsInfo.rds
/usr/lib64/R/library/trimcluster/Meta/package.rds
/usr/lib64/R/library/trimcluster/NAMESPACE
/usr/lib64/R/library/trimcluster/R/trimcluster
/usr/lib64/R/library/trimcluster/R/trimcluster.rdb
/usr/lib64/R/library/trimcluster/R/trimcluster.rdx
/usr/lib64/R/library/trimcluster/help/AnIndex
/usr/lib64/R/library/trimcluster/help/aliases.rds
/usr/lib64/R/library/trimcluster/help/paths.rds
/usr/lib64/R/library/trimcluster/help/trimcluster.rdb
/usr/lib64/R/library/trimcluster/help/trimcluster.rdx
/usr/lib64/R/library/trimcluster/html/00Index.html
/usr/lib64/R/library/trimcluster/html/R.css
/usr/lib64/R/library/trimcluster/tests/examples.R
/usr/lib64/R/library/trimcluster/tests/examples.Rout.save
