#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-trimcluster
Version  : 0.1.6
Release  : 51
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/trimcluster_0.1-6.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/trimcluster_0.1-6.tar.gz
Summary  : Cluster Analysis with Trimming
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# `trimcluster`: Cluster Analysis with Trimming
<!-- badges: start -->
[![CRAN
version](https://www.r-pkg.org/badges/version/trimcluster)](https://cran.r-project.org/package=trimcluster)
[![R-CMD-check](https://github.com/valentint/trimcluster/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/valentint/trimcluster/actions/workflows/R-CMD-check.yaml)
[![Codecov test
coverage](https://codecov.io/gh/valentint/trimcluster/graph/badge.svg)](https://app.codecov.io/gh/valentint/trimcluster)
[![downloads](https://cranlogs.r-pkg.org/badges/trimcluster)](https://cran.r-project.org/package=trimcluster)
[![downloads](https://cranlogs.r-pkg.org/badges/grand-total/trimcluster)](https://cran.r-project.org/package=trimcluster)
[![license](https://img.shields.io/badge/license-GPL--3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0.en.html)

%prep
%setup -q -n trimcluster
pushd ..
cp -a trimcluster buildavx2
popd
pushd ..
cp -a trimcluster buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1751293406

%install
export SOURCE_DATE_EPOCH=1751293406
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/trimcluster/DESCRIPTION
/usr/lib64/R/library/trimcluster/INDEX
/usr/lib64/R/library/trimcluster/Meta/Rd.rds
/usr/lib64/R/library/trimcluster/Meta/features.rds
/usr/lib64/R/library/trimcluster/Meta/hsearch.rds
/usr/lib64/R/library/trimcluster/Meta/links.rds
/usr/lib64/R/library/trimcluster/Meta/nsInfo.rds
/usr/lib64/R/library/trimcluster/Meta/package.rds
/usr/lib64/R/library/trimcluster/NAMESPACE
/usr/lib64/R/library/trimcluster/R/trimcluster
/usr/lib64/R/library/trimcluster/R/trimcluster.rdb
/usr/lib64/R/library/trimcluster/R/trimcluster.rdx
/usr/lib64/R/library/trimcluster/help/AnIndex
/usr/lib64/R/library/trimcluster/help/aliases.rds
/usr/lib64/R/library/trimcluster/help/paths.rds
/usr/lib64/R/library/trimcluster/help/trimcluster.rdb
/usr/lib64/R/library/trimcluster/help/trimcluster.rdx
/usr/lib64/R/library/trimcluster/html/00Index.html
/usr/lib64/R/library/trimcluster/html/R.css
/usr/lib64/R/library/trimcluster/tests/trtest.R
/usr/lib64/R/library/trimcluster/tests/trtest.Rout.save
